### ISSUE TITLE
propTypes and defaultProps 

### ISSUE THREAD

**Issue by hasanmumin** [wasabi-io/bambu#4]
implementing all propTypes and defaultProps 
  * [x] Layout
    - [x] Container
    - [x] Level
    - [x] Media Object
    - [ ] Hero
    - [x] Section
    - [x] Footer
    - [x] Tiles 
  * [x] Form
    - [x] General
    - [x] Input
    - [x] Textarea
    - [x] Select
    - [x] Checkbox
    - [x] Radio
    - [x] File 
  * [x] Elements
    - [x] Box
    - [x] Button
    - [x] Content
    - [x] Delete
    - [x] Icon
    - [x] Image
    - [x] Notification
    - [x] Progress
    - [x] Table
    - [x] Tag
    - [x] Title   
  * [x] Components
    - [x] Breadcrumb
    - [x] Card
    - [x] Dropdown
    - [x] Menu
    - [x] Message
    - [x] Modal
    - [x] Navbar
    - [x] Pagination
    - [x] Panel
    - [x] Tabs

**Comment by kbukum** [comment]
Added defaultProps and propTypes to all components.
